Fixed channel_installer.py not working with the latest
Package Control version due to:
11:24:40:463.493586 3.35e-04 - channel_manager.channel_installer.setup_packages_ignored_list:1545 - Ignoring the packages:      ['AmxxPawn', 'C++', 'DocBlockr', 'FileDiffs', 'LaTeXTools', 'Markdown', 'Notepad++ Color Scheme', 'RemoveNonAsciiChars', 'X86Assembly']
11:24:40:463.671207 1.83e-04 - channel_manager.channel_installer.setup_packages_ignored_list:1546 - Unignoring the packages:    []
Exception in thread Thread-22:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 344, in run
    self._run()
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 351, in _run
    self.setupThread( self.installerProcedements )
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 370, in setupThread
    targetFunction()
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 401, in installerProcedements
    self.handleSetupOperation( self.install_modules )
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 379, in handleSetupOperation
    operationHandler()
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 466, in install_modules
    self.install_stable_packages( packages_to_install )
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 594, in install_stable_packages
    self.ignore_next_packages( package_name, packages_names )
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 1495, in ignore_next_packages
    self.setup_packages_ignored_list( g_next_packages_to_ignore )
  File "Packages/channelmanager/all/channel_manager/channel_installer.py", line 1556, in setup_packages_ignored_list
    self.package_disabler.disable_packages( packages_to_add, ignoring_type )
  File "Installed Packages/Package Control.sublime-package/package_control/package_disabler.py", line 75, in disable_packages
    raise RuntimeError('disable_packages called on a background thread')
RuntimeError: disable_packages called on a background thread